# fly.toml app configuration file generated for angies-twitter-delicate-frog-275 on 2025-03-09T11:44:49+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'angies-twitter-delicate-frog-275'
primary_region = 'hkg'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'angies-twitter-delicate-frog-275.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 10900
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
