name: Release

on:
  push:
    tags:
      - 'v*'

env:
  MIX_ENV: prod

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.7'
          otp-version: '25.3.2.5'

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Build assets
        run: |
          mix assets.deploy
          
          if [ ! -d "_build/prod/priv/static" ]; then
              echo "Assets compilation failed"
              exit 1
          fi

      - name: Build release
        run: |
          mix release

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _build/prod/rel/auth_learning/releases/*/*.tar.gz
            _build/prod/priv/static/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.TWITTER_TOKEN }}