name: Release

on:
  push:
    tags:
      - '**'

env:
  MIX_ENV: prod
  GH_TOKEN: ${{ secrets.TWITTER_TOKEN }}

jobs:
  mix-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.TWITTER_TOKEN }}

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.7'
          otp-version: '25.3.2.5'

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Build assets
        run: |
          mix assets.deploy
          
          if [ ! -d "priv/static" ]; then
              echo "Assets compilation failed"
              exit 1
          fi

      - name: Build release
        run: |
          yes | mix release

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-package
          path: _build/prod/auth_learning*.tar.gz

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _build/prod/auth_learning*.tar.gz
            priv/static/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.TWITTER_TOKEN }}

  version_management:
    needs: mix-release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Get latest version from git tags
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          gh variable set VERSION -e angies-twitter --body "$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version in version_management: $VERSION"

  deploy:
    needs: [mix-release, version_management]
    runs-on: ubuntu-latest
    steps:
      - name: Download release package
        uses: actions/download-artifact@v3
        with:
          name: release-package
          path: release

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Current version: ${{ needs.version_management.outputs.version }}"
            cd twitter_learning/
            sudo systemctl stop auth_learning

      - name: Copy release package to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_KEY }}
          source: "release/*"
          target: "twitter_learning/_build/prod/"
          strip_components: 1

      - name: Extract and start service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd twitter_learning/_build/prod/
            tar xzf auth_learning*.tar.gz -C ~/twitter_learning/_build/prod/rel/auth_learning
            
            # Update VERSION in systemd service file
            sudo sed -i '/Environment="VERSION=/c\Environment="VERSION=${{ needs.version_management.outputs.version }}"' /etc/systemd/system/auth_learning.service
            sudo systemctl daemon-reload
            
            sudo systemctl start auth_learning
            sudo systemctl status auth_learning | cat