name: Release

on:
  push:
    branches: [ '*' ]

env:
  MIX_ENV: prod

jobs:
  mix-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.TWITTER_TOKEN }}

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.7'
          otp-version: '25.3.2.5'

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Build assets
        run: |
          mix assets.deploy
          
          if [ ! -d "priv/static" ]; then
              echo "Assets compilation failed"
              exit 1
          fi

      - name: Build release
        run: |
          mix release

      # - name: Upload release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       _build/prod/auth_learning*.tar.gz
      #       priv/static/**/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TWITTER_TOKEN }}

  # version_management:
  #   needs: mix-release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Get latest version from git tags
  #       id: get_version
  #       run: |
  #         VERSION=$(git describe --tags --abbrev=0)
  #         echo "version=$VERSION" >> $GITHUB_OUTPUT
  #         echo "VERSION=$VERSION" >> $GITHUB_ENV
  #         echo "Current version in version_management: $VERSION"

  #     - name: Set version as environment variable
  #       run: |
  #         echo "Version from get_version step: ${{ steps.get_version.outputs.version }}"
  #         echo "Version from environment: $VERSION"

  deploy:
    needs: mix-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploying version: ${{ steps.version_management.outputs.version }}"
            echo "export VERSION=${{ steps.version_management.outputs.version }}" >> ~/.bashrc
            source ~/.bashrc
            echo "Version in bashrc: $VERSION"
            
            cd twitter_learning/
            sudo systemctl stop auth_learning
            git pull origin main
            MIX_ENV=prod mix release
            sudo systemctl start auth_learning