name: Release

on:
  push:
    branches: [ '*' ]

env:
  MIX_ENV: prod

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.TWITTER_TOKEN }}
      
      - name: Update version in mix.exs
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/version: \".*\"/version: \"$VERSION\"/" mix.exs
          cat mix.exs
          
      - name: Commit version update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add mix.exs
          git commit -m "Update version to $VERSION"
          git push origin main

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.7'
          otp-version: '25.3.2.5'

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Build assets
        run: |
          mix assets.deploy
          
          if [ ! -d "priv/static" ]; then
              echo "Assets compilation failed"
              exit 1
          fi

      - name: Build release
        run: |
          mix release

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _build/prod/auth_learning*.tar.gz
            priv/static/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.TWITTER_TOKEN }}